name: PMD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.38.0/pmd-bin-6.38.0.zip
          unzip pmd-bin-6.38.0.zip
          pmd-bin-6.38.0/bin/run.sh pmd -d . -R pmd.xml -f sarif-2.1.0 -r pmd-results.sarif
          
      - name: Upload PMD Results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: pmd-results.sarif
